### ISSUE TITLE
Sidecar injection with StatefulSet not working

### ISSUE THREAD

**Issue by vbtnickn** [istio/old_issues_repo#121]
**Is this a BUG or FEATURE REQUEST?:**
BUG
**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics):
I did not see any issues relating to this problem
**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
Version: 25d77967f9c28d56317ff31326295c6be4274457
GitRevision: 25d77967f9c28d56317ff31326295c6be4274457
GitBranch: master
User: root@76bade6806e5
GolangVersion: go1.8
kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.9", GitCommit:"19fe91923d584c30bd6db5c5a21e9f0d5f742de8", GitTreeState:"clean", BuildDate:"2017-10-19T17:09:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6+a08f5eeb62", GitCommit:"c84beff", GitTreeState:"clean", BuildDate:"2017-10-27T16:12:40Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
This is running in openshift origin 3.7

**Is Istio Auth enabled or not ?**
Did you install istio.yaml, istio-auth.yaml....
Istio Auth is NOT enabled.  Installed istio.yaml and istio-initializer.yaml

**What happened**:
When trying to deploy a StatefulSet for rabbitmq, the istio-initializer pod reports this error in the pod:

```
E1107 20:01:40.035923      10 initializer.go:153] StatefulSet.apps "rabbitmq" is invalid: spec.template.containers: Forbidden: pod updates may not add or remove containers
```

The StatefulSet is left in the uninitialized state.

**What you expected to happen:**
StatefulSet should start up correctly.

Using the initializer with deployments and pods seems to work fine.  The sidecar gets injected properly.  But it isn't working when used with a StatefulSet.  I tried changing a variety of security settings for different users and pods, but the istio-initializer pod always reported that error when trying to create a StatefulSet.

I ran all of the commands on the istio documentation for using openshift:

```
oc adm policy add-scc-to-user anyuid -z istio-ingress-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-egress-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z default -n istio-system

oc adm policy add-scc-to-user privileged -z default -n <target-namespace>
```

**How to reproduce it:**
Attempt to deploy this StatefulSet to an openshift cluster:

```
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: "rabbitmq"
    service: rabbitmq
spec:
  selector:
    service: rabbitmq
  type: ClusterIP
  ports:
  - name: amqp-tcp
    port: 5672
    targetPort: amqp-tcp
  - name: admin-tcp
    port: 15672
    targetPort: admin-tcp

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rabbitmq
  labels:
    app: "rabbitmq"
    service: rabbitmq
spec:
  serviceName: "rabbitmq"
  replicas: 1
  template:
    metadata:
      labels:
        app: "rabbitmq"
        service: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: "rabbitmq:3.6.6-management-alpine"
        imagePullPolicy: ""
        env:
        - name: RABBITMQ_ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: rabbitmq.cookie
              key: erlang-cookie
        ports:
        - name: amqp-tcp
          containerPort: 5672
        - name: admin-tcp
          containerPort: 15672
        livenessProbe:
          exec:
            command:
            - rabbitmqctl
            - status
          initialDelaySeconds: 120
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - rabbitmqctl
            - status
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 5
        volumeMounts:
        - name: rabbitmq-pvc
          mountPath: /var/lib/rabbitmq
      imagePullSecrets:
      - name: index.docker.io
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-pvc
      annotations:
        description: 'Persistent volume claim for the RabbitMQ queues.'
        volume.beta.kubernetes.io/storage-class: "gold"
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: "200Mi"
```
