### ISSUE TITLE
istio as proxy for external services

### ISSUE THREAD

**Issue by zillani** [istio/old_issues_repo#208]
**ISSUE TYPE: FEATURE REQUEST:**

**Setup:**
istio: v0.5.0
k8s: 1.7.4

**Description:**
I would like to use istio ingress as a proxy for my external services as below,

```
http_proxy=$ISTIO_INGRESS curl -v http://www.foo.bar.com:443
```
discussion on google groups: 
https://groups.google.com/forum/#!topic/istio-users/Y0mAUNMIU30

**Comment by vadimeisenbergibm** [comment]
@zillani to clarify, following the discussion on google groups, how do you want to use that proxy:
1. As you wrote in https://github.com/istio/issues/issues/208#issue-297418284
 `http_proxy=$ISTIO_INGRESS curl -v http://www.foo.bar.com:443`

Or:

2. `curl $ISTIO_INGRESS/foo:443` would be OK, with the request  forwarded to `http://www.foo.bar.com:443` ?

**Comment by zillani** [comment]
@vadimeisenbergibm 
normally with the proxy env variable Option-1, but hey! Option-2 in some usecases will be great as well. Preferably #1 for now.

**Comment by ldemailly** [comment]
not sure either of those are wise from a security point of view

also not clear how that relates to istio's mission as a mesh management - bouncing traffic of the "ingress" seems like a different use case (which you can write as a service if you wanted to)

**Comment by vadimeisenbergibm** [comment]
@zillani Example of the option 2, using istio to become a proxy to `httpbin.org` (works starting from Istio 0.5.1)

1. Define a Kubernetes External Name service:
```yaml
kind: Service
apiVersion: v1
metadata:
  name: externalbin
  namespace: default
spec:
  type: ExternalName
  externalName: httpbin.org
  ports:
  - port: 80
    name: http
```

2. Define Ingress to direct traffic from `$ISTIO_INGRESS/httbin` to `httpbin.org`:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: httpbin-gateway
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - http:
      paths:
      - path: /httpbin/.*
        backend:
          serviceName: externalbin
          servicePort: 80
```

3. Define a Route Rule to remove `/httbin` prefix and to rewrite the `Host` header to be `httpbin.org`:
 ```yaml
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: externalbin-route-rule
  namespace: default
spec:
  destination:
    name: externalbin
  match:
    request:
      headers:
        uri:
          prefix: "/httpbin"
  rewrite:
    uri: "/"
    authority: httpbin.org
```
4. Access, for example, `$INGRESS_HOST/httpbin/headers`. The output should be similar to the following:
```json
{
  "headers": {
    "Accept": "*/*", 
    "Connection": "close", 
    "Host": "httpbin.org", 
    "X-Envoy-Decorator-Operation": "externalbin-route-rule", 
    "X-Envoy-Internal": "true", 
    "X-Envoy-Original-Path": "/httpbin/headers", 
  }
}
```
