### ISSUE TITLE
cookie match is not working 

### ISSUE THREAD

**Issue by DanielWangZhanggui** [istio/old_issues_repo#297]
**Is this a BUG or FEATURE REQUEST?:**
BUG
**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:
Yes

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version 7.1
kubectl version 1.10.1
```

**Is Istio Auth enabled or not ?** 
Did you install the stable istio.yaml, istio-auth.yaml....  or if using the Helm chart please provide full command line input.
Using istio.yaml

**What happened**:
Route rule file is:
```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: cpuload
spec:
  destination:
    name: cpuload
  match:
    request:
      headers:
        cookie:
          regex: "^(.*?;)?(userType=p)(;.*)?$"
  route:
  - labels:
      version: v2
```
Once I'm using cookie to check http request header, the envoy in ingress will return 404
If I change "match" to  some specific http header, like using  "exact", it works.

**What you expected to happen:**
When I using cookie to check http request, it should return to my cpuload v2 version
**How to reproduce it:**
kubernetes yaml files： 
```
apiVersion: v1
kind: Service
metadata:
  name: cpuload
  labels:
    app: cpuload
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: cpuload
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cpuloadv1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cpuload
        version: v1
    spec:
      containers:
      - name: cpuload
        image: burning1docker/cpuload:V1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 500m
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cpuloadv2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cpuload
        version: v2
    spec:
      containers:
      - name: cpuload
        image: burning1docker/cpuload:V2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 500m
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /.*
        backend:
          serviceName: cpuload
          servicePort: 8080
```
Please help, thanks in advance!

All the best,
Daniel
