### ISSUE TITLE
httpFault route does not work + slow response via istio proxies

### ISSUE THREAD

**Issue by utrack** [istio/old_issues_repo#310]
**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**: Yes

**Bug:**
Y?

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
» kubectl version                                                                     2018-04-28 14:26:05
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

λ ~
» istioctl version                                                                    2018-04-28 14:26:08
Version: 0.7.1
GitRevision: 62110d4f0373a7613e57b8a4d559ded9cb6a1cc8
User: root@c5207293dc14
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean
```

**Is Istio Auth enabled or not ?**
Nope

**What happened**:
I've deployed my sample Hello World service:
```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: catalog-api-test-master
  namespace: default
spec:
  destination:
    name: catalog-api
  precedence: 1
  httpFault:
    abort:
      httpStatus: 418
      percent: 100
  route:
  - labels:
      app: catalog-api
      version: master
```
```
apiVersion: v1
kind: Service
metadata:
  name: catalog-api
  labels:
    app: catalog-api
spec:
  ports:
  - port: 8090
    name: http
  - port: 8443
    name: grpc
  selector:
    app: catalog-api
```
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalog-api-master
  labels:
    app: catalog-api
spec:
  replicas: 
  template:
    metadata:
      labels:
        app: catalog-api
        version: master
    spec:
      containers:
      - name: catalog-api
        image: myreg/bx/catalog-api:master
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8090
        - name: grpc
          containerPort: 8443
      imagePullSecrets:
      - name: gtlregkey
```

**What you expected to happen:**
GET /hello should return 418. It returns 200 after 2s delay (should've taken ~15ms tops?).

**Comment by utrack** [comment]
Route description:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simple-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - http:
      paths:
      - path: /hello
        backend:
          serviceName: catalog-api
          servicePort: 8090
```
