### ISSUE TITLE
TCP routing rules are ignored

### ISSUE THREAD

**Issue by mydoal** [istio/old_issues_repo#334]
**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
Version: release-0.8-20180504-17-20
GitRevision: 1ec141e7b9a735c6bcc2b4fae29c6924bc94c49b
User: root@20f3450616f6
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:59:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:
```

**Is Istio Auth enabled or not ?**

Installed from:
https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-0.8-20180504-17-20/

**What happened**:

TCP Routing rules are ignored.
Services in the mesh that use "service-mongodb" on port 80 keep reaching that service instead of being forwarded to port 27018 as defined in the routing rules.

**What you expected to happen:**
Services in the mesh that use "service-mongodb" should be routed to port 27018.

**How to reproduce it:**

service-mongodb is defined in a yaml file 
```
apiVersion: v1
kind: Service
metadata:
  name: service-mongodb
  labels:
    app: service-mongodb
spec:
  selector:
    app: service-mongodb
  ports:
  - port: 80
    targetPort: 27017
    name: mongo
    protocol: TCP
```

and deployed to kubernetes using:
```
kubectl apply -f <(istioctl kube-inject --debug -f mongodb.yaml)
```

TCP Routing Rules
```
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service-mongodb-route
spec:
  hosts:
  - service-mongodb
  tcp:
  - match:
    - port: 80
      sourceSubnet: "0.0.0.0/0"
    route:
    - destination:
        host: service-mongodb
        port:
          number: 27018
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: service-mongodb-destination
spec:
  host: service-mongodb
```

**Feature Request:**
Y/N

**Describe the feature:**
