### ISSUE TITLE
Fails to launch a job with auto injection

### ISSUE THREAD

**Issue by sgandon** [istio/old_issues_repo#345]
**Is this a BUG or FEATURE REQUEST?:**
Bug

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
Version: 0.7.1
GitRevision: 62110d4f0373a7613e57b8a4d559ded9cb6a1cc8
User: root@c5207293dc14
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean

kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?**
no Auth
I installed `install/kubernetes/istio.yaml` on my docker-for-mac K8s cluster
and installed the side car injector
`install/kubernetes/istio-sidecar-injector.yaml`

**What happened**:
when I install a K8s job, it never succeeds

**What you expected to happen:**
job to end sucessfully

**How to reproduce it:**
just install this manifest using `kubectl create -f `
```
apiVersion: batch/v1
kind: Job
metadata:
  name: test-init-postgresql-embedded-secret-job
  annotations:
  labels:
    app: infra-tpostgresql
    chart: tpostgresql
    release: infra
    heritage: Tiller
spec:
  template:
    metadata:
    spec:
      containers:
      - name: infra-init-postgresql-secret-job
        image: dtzar/helm-kubectl:2.8.0
        command: ["sh", "-c", "RESULT=$(kubectl create secret generic $SECRET_NAME --namespace $SECRET_NAMESPACE --from-literal='postgresql.host'=$POSTGRESQL_HOST --from-literal='postgresql.user'=$POSTGRESQL_USER --from-literal='postgresql.password'=$POSTGRESQL_PASSWORD --from-literal='postgresql.database'=$POSTGRESQL_DATABASE --from-literal='postgresql.port'=$POSTGRESQL_PORT 2>&1); EXIT_CODE=$?; echo $RESULT | grep -q \"AlreadyExists\"; if [ $? = 0 ]; then echo 0; else echo $RESULT; echo $EXIT_CODE; fi;"]
        env:
          - name: POSTGRESQL_HOST
            value: infra-postgresqlembedded
          - name: SECRET_NAME
            value: infra-postgresql-master-secret
          - name: SECRET_NAMESPACE
            value: default
          - name: POSTGRESQL_USER
            value: master-user
          - name: POSTGRESQL_PASSWORD
            value: master-user
          - name: POSTGRESQL_DATABASE
            value: dbname
          - name: POSTGRESQL_PORT
            value: "5432"
      restartPolicy: Never
```
What this job does is irrelevent.
What seems to happends is that the injected envoy proxy keeps running and therefore make the job to never end, which is not expected for a job.
Of course this works fine if we add the annotation 
```
      annotations:
        sidecar.istio.io/inject: "false"
```
But what if the job wants to call outside the container using the service mesh ?
